./" Manpage for snake.sh
.TH man 6 "21.04.2024" "1.0" "snake.sh man page"
.SH NAME
snake.sh \- simple snake game written in bash
.SH SYNOPSIS
.B snake.sh [\-h] [\-v] [\-a <number>] [\-s <number>]
.SH DESCRIPTION
Skrypt to prosta gra węża napisana w bashu. Gra polega na zbieraniu jabłek przez węża.
.P
Gracz steruje wężem za pomocą klawiszy WSAD. Jabłka są generowane losowo na planszy. Po zebraniu jabłka, jego pozycja jest resetowana, a wąż wydłuża się o jeden kwadrat. Prędkość węża jest zwiększana po zebraniu każdego jabłka. Gra kończy się, gdy wąż uderzy w ścianę lub w siebie.
.SH OPTIONS
The script supports the following options:
.TP
.B \-h
Display help message and exit.
.TP
.B \-v
Display version message and exit.
.TP
.B \-a
Set apple count.
.TP
.B \-s
Set snake length.
.SH BUGS
No known bugs.
.SH AUTHOR
Stanisław Rzeszut (s198318@student.pg.edu.pl)
.SH REPORTING BUGS
https://gh.kums.dev/snake.sh